version: "5"
services:
  appserver:
    image: nivitzhaky/basic-spring:niv-001
    ports:
      - 8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    privileged: true