apiVersion: apps/v1
kind: Deployment #Pod/ Service/ Deployment
metadata:
  labels:
    app: postgres
    openshift.io/deployment-config.name: postgres
    template: postgresql-ephemeral-template
  name: postgres-1
spec:
  replicas: 1 # num of rep
  selector:
    matchLabels:
      app: postgres # Important
  template:
    metadata:
      labels:
        app: postgres
        name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: postgres
          # image name
          image: >- 
            centos/postgresql-95-centos7@sha256:d459c9bb18ec7de443fbe4dd31cff26bdc6fdc681363922e97ae2f40e64a93c1
          imagePullPolicy: IfNotPresent
          name: postgresql # name
          ports:
            - containerPort: 5432 # Output to export ports
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/pgsql/data # save of HD
              name: postgres-data
      volumes:
        - emptyDir: {}
          name: postgres-data
